@DotnetBarcelona.Actors.WebAPI_HostAddress = http://localhost:5121

GET {{DotnetBarcelona.Actors.WebAPI_HostAddress}}/actors/
Accept: application/json

###


POST {{DotnetBarcelona.Actors.WebAPI_HostAddress}}/actors/
Content-Type: application/json
{
  "name": "",
  "dateOfBirth": "",
  "nationality": ""
}

###

GET {{DotnetBarcelona.Actors.WebAPI_HostAddress}}/actor/5
Accept: application/json
###
